### ISSUE TITLE
StageAttributes

### ISSUE THREAD

**Issue by wzorgdrager** [codefeedr/codefeedr#100]
Is stageAttributes.id also used as topic name/subject?

**Comment by joskuijpers** [comment]
Pipelineobject.id defaults to className but overrides with stageatrrivutes.id. The kafka topic defaults to the stage id that sends into it. The kafka group id defaullts to the stage id of the reader but is overridden by --groupId in cluster mode

**Comment by wzorgdrager** [comment]
Hmm I don't think so about the topic, if I look at the create function of the BufferFactory it retrieves the subject by calling `sinkObject.getSinkSubject` (see [here](https://github.com/joskuijpers/bep_codefeedr/blob/7d702d35316c5c508c03801007da9ee6acd84e9d/codefeedr-core/src/main/scala/org/codefeedr/buffer/BufferFactory.scala#L53)). If we then look to getSinkSubject, it just retrieves `this.getClass.getName` (see [here](https://github.com/joskuijpers/bep_codefeedr/blob/7d702d35316c5c508c03801007da9ee6acd84e9d/codefeedr-core/src/main/scala/org/codefeedr/pipeline/PipelineObject.scala#L145)). So it doesn't default to the stage id of its parent, it defaults to the class name of its parent. Is this desired?

**Comment by joskuijpers** [comment]
No it isn't. That should be changed to this.id.
