### ISSUE TITLE
Create is called twice in buffer factory

### ISSUE THREAD

**Issue by wzorgdrager** [codefeedr/codefeedr#101]
Why does a stage call `create` two times on the bufferfactory? I understand you need a buffer both to read and write from, but why is getSinkSubject then also called twice?

**Comment by joskuijpers** [comment]
Assume a pipeline with Stage A, B and C (in sequence).
There are 2 buffers, U, between A and B, and V, between B and C.
So the flow is:
`A -> U -> B -> V -> C`

If stage B starts, it needs to read from buffer U and write to buffer V.
PipelineObject for B calls getMainSource. The topic of that buffer equals the topic of the buffer A writes to. So the parent is taken (A), and its sink topic is requested.
Then the sink buffer is created, for which getSinkSubject is called on the stage itself (B).

So:
`B.createSource -> A.getSinkSubject -> BufferFactory.create`
`B.createSink -> B.getSinkSubject -> BufferFactory.create`
