### ISSUE TITLE
Kryo serialization test

### ISSUE THREAD

**Issue by wzorgdrager** [codefeedr/codefeedr#105]
Test whether Kryo supports the following serde:

```scala
case class Test(hi: String, bye: Int)
case class Test2(hi: String)

deserialize[Test2](serialize(Test("hi, 1)))
```

**Comment by jorisquist** [comment]
I've tested this and this is not possible at the moment. It might work if we could use this: https://github.com/EsotericSoftware/kryo#compatiblefieldserializer, but I'm not sure if this is possible with twitter/chill and if we would want to use this.
