### ISSUE TITLE
Change retention time kafka

### ISSUE THREAD

**Issue by jorisquist** [codefeedr/codefeedr#113]

**Comment by wzorgdrager** [comment]
I'm not sure if we should support this. Apparently retention time in Kafka is cluster-wide and you need to configure it through the broker (not per topic).

**Comment by wzorgdrager** [comment]
I could connect to the Kafka broker and set this, however it is cluster-wide so if you run multiple pipelines on 1 cluster only the last retention time set is used. 

EDIT: Nevermind that is not an option. If users want to set the retention time, they should change it in the server.properties of Kafka.
