### ISSUE TITLE
Rename GHTorrent plugin stages

### ISSUE THREAD

**Issue by wzorgdrager** [codefeedr/codefeedr#206]
Currently stages for GHTorrent are named:
` GHTRecordTo#EVENT_NAME#Stage`, maybe those name are too long and we should go for something like this:
- `GHTPushEventStage`
or 
- `PushEventStage`
or
- `GHTPushEvent`

**Comment by gousiosg** [comment]
I'd vote for `GHTPushEventStage`

**Comment by wzorgdrager** [comment]
Reflected in #190
