### ISSUE TITLE
Renaming & conventions

### ISSUE THREAD

**Issue by wzorgdrager** [codefeedr/codefeedr#64]
I think we should rename some classes:
- RSSInputStage: obviously it is a stage, maybe just RSSInput
- LogInputStage: same thing, just LogInput?

Maybe we should create some 'conventions' for a plugin:
- Stages should have a class name which are self-explanatory (and not contain the word stage/input/output)?
- All stages should be put under a /stages folder in a plugin? Maybe too much overkill especially for the smaller plugins, however it does make clear distinction between actual stages/flink-sources/flink-sink/utility classes?

Could someone also check the names of classes in the GitHub plugin? We might want to refactor this 
in the restructuring branch as well. 

What do you think? @Jorisq @joskuijpers

**Comment by joskuijpers** [comment]
We could separate the stages into .stages and flink sinks and stuff into .flink, for example.

Not sure about the naming, removing Stage. It is not obvious it is a stage when using it, maybe.

Would also become GithubEventsInput, GithubEventsTransform

**Comment by joskuijpers** [comment]
...Input
...Output
...To..Transform

**Comment by joskuijpers** [comment]
Done
