### ISSUE TITLE
Use com.typesafe.config for configuration

### ISSUE THREAD

**Issue by gousiosg** [codefeedr/codefeedr#75]
We are currently using configuration strings (e.g. connection strings, etc) allover the place in the code. It would be nice if we could replace them with the [Lightbend/Typesafe config](https://github.com/lightbend/config) library. We are using this in the other Codefeedr repo with excellent results.

**Comment by joskuijpers** [comment]
Can you point to where we use 'configuration strings'? Most of the strings I see are default values that we would require no matter what.

**Comment by gousiosg** [comment]
Yes, but in a real deployment you would need to configure them through either external config files or (better) environment variables. Config allows you to have those defaults you mention and also configure real deployments without touching the src code.

**Comment by joskuijpers** [comment]
Yes.

However, this is a framework, so it would go like this:

You make a new SBT project that has a `org.codefeedr % codefeedr-core` dependency. Then you have a main file:

`Main.scala`
```scala
object Main {

  def main(args: Array[String]) = {
    val pipeline = new PipelineBuilder()
        .setBufferType(BufferType.Kafka),
        .setBufferProperty(Buffer.HOST, "localhost:12345")
        .append(new StringInput("hello world"))
        .append(new MongoOutput("db", "collection", "mongodb://localhost:98765"))
        .build()

    pipeline.start(args)
  }

}
```

This is your program, and indeed has configuration strings int here. So here you could replace them with the typesafe/lightbend thing yourself, by adding lightbend as a dependency and doing this:

```scala
object Main {

  def main(args: Array[String]) = {
    val conf = ConfigFactory.load()

    val pipeline = new PipelineBuilder()
        .setBufferType(BufferType.Kafka),
        .setBufferProperty(Buffer.HOST, conf.getString("kafka.host"))
        .append(new StringInput("hello world"))
        .append(new MongoOutput(conf.getString("mongo.db"), conf.getString("mongo.outputCollection"), conf.getString("mongo.host")))
        .build()

    pipeline.start(args)
  }

}
```

This allows for ultimate flexibility: There can be multiple inputs, multiple mongo outputs with different configurations, and so on. The user of the framework is not bound to using lightbend but can do whatever it want.

And for just a student making a small project, using separate config files is not much easier than just typing it in Scala with type checking.
