### ISSUE TITLE
Add Context to Stages

### ISSUE THREAD

**Issue by wzorgdrager** [codefeedr/codefeedr#84]
E.g.

`main(ctx : Context) : DataStream[In]`
`transform(input: DataStream[In], ctx : Context) : DataStream[Out]`
`main(DataStream[In], ctx: Context)`

Then `Context` could contain:
- Keymanager
- Flink environment
- Stageproperties?
- ..

Maybe even adding `StreamExecutionEnvironment` as parameter for InputStage main:
`main(env : StreamExecutionEnvironment, ctx : Context) : DataStream[In]` or
`main(env : StreamExecutionEnvironment) : DataStream[In]`

instead of `pipeline.environment` or `context.environment`

**Comment by joskuijpers** [comment]
Will add

```scala
def environment = pipeline.environment
```

**Comment by wzorgdrager** [comment]
I will add this in my twitter branch, since I need it for some mocking.

**Comment by wzorgdrager** [comment]
Fixed in #106
